cityscapes_dataset:
  unlabeled:
    category: void
    color:
      - 0
      - 0
      - 0
    id: 0
    train_id: 255
    priseg_id: 0
  ego_vehicle:
    category: void
    color:
      - 0
      - 0
      - 0
    id: 1
    train_id: 255
    priseg_id: 0
  rectification_border:
    category: void
    color:
      - 0
      - 0
      - 0
    id: 2
    train_id: 255
    priseg_id: 0
  out of roi:
    category: void
    color:
      - 0
      - 0
      - 0
    id: 3
    train_id: 255
    priseg_id: 0
  static:
    category: void
    color:
      - 0
      - 0
      - 0
    id: 4
    train_id: 255
    priseg_id: 3
  dynamic:
    category: void
    color:
      - 111
      - 74
      - 0
    id: 5
    train_id: 255
    priseg_id: 3
  ground:
    category: void
    color:
      - 81
      - 0
      - 81
    id: 6
    train_id: 255
    priseg_id: 1
  road:
    category: flat
    color:
      - 128
      - 64
      - 128
    id: 7
    train_id: 0
    priseg_id: 5
  sidewalk:
    category: flat
    color:
      - 244
      - 35
      - 232
    id: 8
    train_id: 1
    priseg_id: 1
  parking:
    category: flat
    color:
      - 250
      - 170
      - 160
    id: 9
    train_id: 255
    priseg_id: 1
  rail_track:
    category: flat
    color:
      - 230
      - 150
      - 140
    id: 10
    train_id: 255
    priseg_id: 1
  building:
    category: construction
    color:
      - 70
      - 70
      - 70
    id: 11
    train_id: 2
    priseg_id: 3
  wall:
    category: construction
    color:
      - 102
      - 102
      - 156
    id: 12
    train_id: 3
    priseg_id: 3
  fence:
    category: construction
    color:
      - 190
      - 153
      - 153
    id: 13
    train_id: 4
    priseg_id: 3
  guard_rail:
    category: construction
    color:
      - 180
      - 165
      - 180
    id: 14
    train_id: 255
    priseg_id: 3
  bridge:
    category: construction
    color:
      - 150
      - 100
      - 100
    id: 15
    train_id: 255
    priseg_id: 3
  tunnel:
    category: construction
    color:
      - 150
      - 120
      - 90
    id: 16
    train_id: 255
    priseg_id: 3
  pole:
    category: object
    color:
      - 153
      - 153
      - 153
    id: 17
    train_id: 5
    priseg_id: 3
  polegroup:
    category: object
    color:
      - 153
      - 153
      - 153
    id: 18
    train_id: 255
    priseg_id: 3
  traffic_light:
    category: object
    color:
      - 250
      - 170
      - 30
    id: 19
    train_id: 6
    priseg_id: 3
  traffic_sign:
    category: object
    color:
      - 220
      - 220
      - 0
    id: 20
    train_id: 7
    priseg_id: 3
  vegetation:
    category: nature
    color:
      - 107
      - 142
      - 35
    id: 21
    train_id: 8
    priseg_id: 0
  terrain:
    category: nature
    color:
      - 152
      - 251
      - 152
    id: 22
    trainId: 9
    priseg_id: 1
  sky:
    category: sky
    color:
      - 70
      - 130
      - 180
    id: 23
    train_id: 10
    priseg_id: 4
  person:
    category: human
    color:
      - 220
      - 20
      - 60
    id: 24
    train_id: 11
    priseg_id: 3
  rider:
    category: human
    color:
      - 255
      - 0
      - 0
    id: 25
    train_id: 12
    priseg_id: 3
  car:
    category: vehicle
    color:
      - 0
      - 0
      - 142
    id: 26
    train_id: 13
    priseg_id: 3
  truck:
    category: vehicle
    color:
      - 0
      - 0
      - 70
    id: 27
    train_id: 14
    priseg_id: 3
  bus:
    category: vehicle
    color:
      - 0
      - 60
      - 100
    id: 28
    train_id: 15
    priseg_id: 3
  caravan:
    category: vehicle
    color:
      - 0
      - 0
      - 90
    id: 29
    train_id: 255
    priseg_id: 3
  trailer:
    category: vehicle
    color:
      - 0
      - 0
      - 110
    id: 30
    trainId: 255
    priseg_id: 3
  train:
    category: vehicle
    color:
      - 0
      - 80
      - 100
    id: 31
    trainId: 16
    priseg_id: 3
  motorcycle:
    category: vehicle
    color:
      - 0
      - 0
      - 230
    id: 32
    train_id: 17
    priseg_id: 3
  bicycle:
    category: vehicle
    color:
      - 119
      - 11
      - 32
    id: 33
    train_id: 18
    priseg_id: 3
  license_plate:
    category: vehicle
    color:
      - 0
      - 0
      - 142
    id: -1
    train_id: -1
    priseg_id: 3
