logs_config:
  version: 1
  disable_existing_loggers: true

  formatters:
    standard:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    error:
      format: '%(asctime)s - %(name)s - %(funcName)s(): - %(levelname)s - %(message)s'

  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: standard
      stream: ext://sys.stdout

    debug_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: standard
      filename: debug.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8

    info_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: standard
      filename: info.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8

    warn_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: WARN
      formatter: standard
      filename: warnings.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8

    error_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: ERROR
      formatter: error
      filename: errors.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8

    critical_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: CRITICAL
      formatter: standard
      filename: critical.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8

  root:
    level: DEBUG
    handlers: [ console,
                debug_file_handler,
                info_file_handler,
                warn_file_handler,
                error_file_handler,
                critical_file_handler ]
    propagate: yes

  loggers:
    <module>:
      level: DEBUG
      handlers: [ console,
                  debug_file_handler,
                  info_file_handler,
                  warn_file_handler,
                  error_file_handler,
                  critical_file_handler ]
      propagate: yes

    <module.x>:
      level: DEBUG
      handlers: [ console,
                  debug_file_handler,
                  info_file_handler,
                  warn_file_handler,
                  error_file_handler,
                  critical_file_handler ]
      propagate: yes