test_params:
  img_size: [ 320, 512 ]
  model_name: "Resnet34.pt"
  rellis_path: '/home/ales/Datasets/Rellis_3D'
  rugd_path: '/home/ales/Datasets/RUGD'
  cityscapes_path: '/home/ales/Datasets/cityscapes'