root: ''
src: 'src'
dataset: 'data'
config: 'config'
models: 'models'
logs: 'log/logs'
utils: 'src/utils'
plots: 'results/plots'
rellis: '/home/ales/Datasets/Rellis_3D'
rugd: '/home/ales/Datasets/RUGD'
cityscapes: '/home/ales/Datasets/cityscapes'